# Replica count for the backend deployment
replicaCount: 2

# name of resources such as deployment, container, service
name: backend

# Image repository and tag for the backend container
image:
  repository: sieunhantanbao/backend
  tag: latest
  pullPolicy: Always
  imagePullSecret: 'qa-acr-secret'

# Port for the backend service
servicePort: 3000